version: '3'
volumes:
  pgdata:
    driver: "local"
services:
  db:
    #image: postgres:11
    container_name: pgsql11
    build: "./app/pgsql"
    command: 'postgres -c config_file="/etc/postgresql.conf"'
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: P@ssw0rd
    volumes:
      - "pgdata:/var/lib/postgresql/data"
      - "./res/pgsql/postgresql.conf:/etc/postgresql.conf"
      - "./init:/docker-entrypoint-initdb.d"
    ports:
      - 5432:5432
